feat: design polishing
technologiestiftung/stakeholder-radar pull request #14
Opened 2024-08-15 08:45 UTC by raphael-arce

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207953913743720
  - https://app.asana.com/0/0/1207922642142795

2024-08-15 09:51 UTC, julizet requested changes

2024-08-15 09:51 UTC, julizet commented on src/components/tags.tsx
> +				<div className="flex gap-x-3 max-w-[50rem] flex-wrap gap-y-3 justify-center">
the tags should fit on two lines on 13" so the tags sections need to be a little bit wider

2024-08-15 09:51 UTC, julizet commented on src/components/dialog.tsx
To avoid the line break we want to move "Website besuche" below the paragraph at the end of the dialogue.
<img width="528" alt="Screenshot 2024-08-15 at 11 47 34" src="https://github.com/user-attachments/assets/6759820f-c6a4-4188-bef4-16e7eb75efdb">

Otherwise looking good!

2024-08-15 10:15 UTC, raphael-arce commented
@julizet okay, I implemented your feedback, could you have another look? 🙏

2024-08-16 06:44 UTC, julizet commented
> @julizet okay, I implemented your feedback, could you have another look? 🙏

looks good to me! :)

2024-08-16 06:45 UTC, merged